### ISSUE TITLE
Update build instructions

### ISSUE THREAD

**Issue by jdknives** [skycoin/wiki#4]
We need instructions on how to build the project. That includes

- getting `mkdocs`
- getting the `material` theme
- getting he `git-revision-date` plugin
- getting the macros plugin
- serving the wiki locally

**Comment by jdknives** [comment]
Note that to some issues with the `macros` plugin, you need to install v1.1.0 with `pip`. Latest version of `mkdocs` breaks the plugin.

**Comment by 4rchim3d3s** [comment]
The command to install mkdocs-material also installs mkdocs itself, so I hope this works. 
As I haven't updated my installation for months I don't know if the problem with the macros plugin also is true with the way I installed it / documented it now.
